AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Auth microservice

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    Handler: src/handler.handler

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Environment:
        Variables:
          TABLE_NAME: !Ref AuthTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /auth
            Method: get
        HealthEvent:
          Type: Api
          Properties:
            Path: /auth/health
            Method: get

  AuthTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint for Auth service"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: AuthServiceApiUrl
