AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Products microservice
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    Handler: src/handler.handler
Resources:
  ProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-artifacts-sudarshantanwer-20251218-1/0c849a2b04b17cf1e14083eb7750c842
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ProductsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /products
            Method: get
    Metadata:
      SamResourceId: ProductsFunction
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    Metadata:
      SamResourceId: ProductsTable
Outputs:
  ApiUrl:
    Description: API Gateway endpoint for Products service
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
    Export:
      Name: ProductsServiceApiUrl
