AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Users microservice
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    Handler: src/handler.handler
Resources:
  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-artifacts-sudarshantanwer-20251218-1/34e728410caeb27b2602eb46e3496a3e
      Environment:
        Variables:
          TABLE_NAME:
            Ref: UsersTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users
            Method: get
    Metadata:
      SamResourceId: UsersFunction
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    Metadata:
      SamResourceId: UsersTable
Outputs:
  ApiUrl:
    Description: API Gateway endpoint for Users service
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
    Export:
      Name: UsersServiceApiUrl
