AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Payments microservice

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    Handler: src/handler.handler

Resources:
  PaymentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Environment:
        Variables:
          TABLE_NAME: !Ref PaymentsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /payments
            Method: post

  PaymentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
